Create popup info view
iOSKirill/PulseWave pull request #4
Opened 2023-12-08 18:23 UTC by iOSKirill

1. Added popup info view. 
2. There is a problem when opening popup info, the blur is not superimposed on the button that is located in the NavigationBar.

2023-12-08 20:47 UTC, vkostechko-applace reviewed
<img width="1124" alt="HeartRateMonitorApp_—_CustomPopupVStackInfo_swift" src="https://github.com/iOSKirill/Heart-Rate-Monitor-and-Pulse-App/assets/152169284/4b29cb85-313c-4ba2-a978-92ddd76a3816">
please fix warnings

2023-12-08 20:50 UTC, ghost reviewed
<img width="292" alt="HeartRateMonitorApp_—_TabBarView_swift" src="https://github.com/iOSKirill/Heart-Rate-Monitor-and-Pulse-App/assets/152169284/3bc6a20f-c95b-49df-871f-5fca8431c807">

2023-12-08 20:55 UTC, vkostechko-applace reviewed
<img width="803" alt="iPhone_15_Pro_and_Heart_Rate_Monitor___Pulse_App_and_HeartRateMonitorApp_—_TabBarView_swift" src="https://github.com/iOSKirill/Heart-Rate-Monitor-and-Pulse-App/assets/152169284/344a8dfc-7d32-437e-a83b-3e3ff30be446">

2023-12-08 20:56 UTC, vkostechko-applace reviewed
![simulator_screenshot_5CD7F093-4352-4E5C-8745-04EC614E1566](https://github.com/iOSKirill/Heart-Rate-Monitor-and-Pulse-App/assets/152169284/79f36889-a78f-4d11-a7ee-dedf8a62f9fa)

2023-12-08 21:00 UTC, ghost requested changes

2023-12-08 21:00 UTC, ghost commented on HeartRateMonitorApp/HeartRateMonitorApp/HomeHealthModule/View/HomeHealthView.swift
> +                }
please present popup with animation

2023-12-08 21:00 UTC, ghost commented on HeartRateMonitorApp/HeartRateMonitorApp/HomeHealthModule/View/HomeHealthView.swift
> +                        Text("OK")
please localize

2023-12-12 16:44 UTC, iOSKirill commented on HeartRateMonitorApp/HeartRateMonitorApp/HomeHealthModule/View/HomeHealthView.swift
> +                }
Fixed

2023-12-12 16:44 UTC, iOSKirill commented on HeartRateMonitorApp/HeartRateMonitorApp/HomeHealthModule/View/HomeHealthView.swift
> +                        Text("OK")
Fixed

2023-12-12 22:04 UTC, ghost commented on HeartRateMonitorApp/HeartRateMonitorApp/CustomViews/CustomNavigationBar.swift
> +struct ScrollPreKey: PreferenceKey {
ScrollPreferenceKey will be better name

2023-12-12 22:04 UTC, ghost commented on HeartRateMonitorApp/HeartRateMonitorApp/CustomViews/CustomNavigationBar.swift
> +    @Binding var isScroll: Bool
what does it mean? is scroll what? is scrolling? or is it scroll view?

2023-12-12 23:26 UTC, ghost requested changes

2023-12-12 23:26 UTC, ghost commented on HeartRateMonitorApp/HeartRateMonitorApp/HomeHealthModule/View/HomeHealthView.swift
> +                    withAnimation(.linear(duration: 0.5)) {
oh, it looks too slow
try this one, looks much better from my point of view 
`withAnimation(.easeInOut(duration: 0.3)) {`

2023-12-12 23:26 UTC, ghost commented on HeartRateMonitorApp/HeartRateMonitorApp/HomeHealthModule/View/HomeHealthView.swift
> +                    withAnimation(.linear(duration: 0.5)) {
dismiss also should be with animation

2023-12-12 23:26 UTC, ghost commented on HeartRateMonitorApp/HeartRateMonitorApp/HomeHealthModule/View/HomeHealthView.swift
> +                    .statusBar(hidden: true)
don't hide the status bar, the content jumps up, it looks weird

2023-12-12 23:31 UTC, ghost reviewed
![simulator_screenshot_CAF7FDFD-3A46-47DF-8261-63A779EA1FD1](https://github.com/iOSKirill/Heart-Rate-Monitor-and-Pulse-App/assets/152169284/ec0870e5-e02c-41ee-a4e8-f4a130106b37)

2023-12-13 20:25 UTC, iOSKirill commented on HeartRateMonitorApp/HeartRateMonitorApp/HomeHealthModule/View/HomeHealthView.swift
> +                    .statusBar(hidden: true)
Fixed

2023-12-13 20:25 UTC, iOSKirill commented on HeartRateMonitorApp/HeartRateMonitorApp/HomeHealthModule/View/HomeHealthView.swift
> +                    withAnimation(.linear(duration: 0.5)) {
Fixed

2023-12-13 20:25 UTC, iOSKirill commented on HeartRateMonitorApp/HeartRateMonitorApp/HomeHealthModule/View/HomeHealthView.swift
> +                    withAnimation(.linear(duration: 0.5)) {
Fixed

2023-12-13 20:25 UTC, iOSKirill commented on HeartRateMonitorApp/HeartRateMonitorApp/CustomViews/CustomNavigationBar.swift
> +    @Binding var isScroll: Bool
Fixed

2023-12-13 20:26 UTC, iOSKirill commented on HeartRateMonitorApp/HeartRateMonitorApp/CustomViews/CustomNavigationBar.swift
> +struct ScrollPreKey: PreferenceKey {
Fixed

2023-12-13 21:49 UTC, ghost approved these changes

2023-12-13 21:49 UTC, merged